### ISSUE TITLE
Por Cliente

### ISSUE THREAD

**Issue by MVinicyuss** [jeovanedossantossantos/back_pr_bd#31]
Na consulta Anterior, eu desejo poder listar por Cpf do cliente Proprietário.

**Comment by jopdaltro** [comment]
SELECT funcionario.*
FROM funcionario
JOIN clienteProprietario ON funcionario.cpf = clienteProprietario.cpf
WHERE clienteProprietario.cpf = 'CPF que queremos buscar';

**Comment by MVinicyuss** [comment]
SELECT ca.id, ca.data_transacao FROM contratoAluguel ca
                INNER JOIN imovel i                 on i.id = ca.id_imovel
                INNER JOIN registroImovel ri        on ri.id_imovel = i.id
                INNER JOIN clienteProprietario cp   on cp.id = ri.id_clientep
                WHERE cp.cpf = ?

SELECT cv.id, cv.data_transacao FROM contratoVenda cv
                INNER JOIN imovel i                 on i.id = cv.id_imovel
                INNER JOIN registroImovel ri        on ri.id_imovel = i.id
                INNER JOIN clienteProprietario cp   on cp.id = ri.id_clientep
                WHERE cp.cpf = ?
